spring:
  cloud:
    gateway:
      routes:
      - id: ORDERS
        uri: lb://ORDERS
        predicates:
        - Path=/api/orders
      - id: PRODUCTS
        uri: lb://PRODUCTS
        predicates:
        - Path=/api/product